version: "3"
services:
  api:
    container_name: api
    build: api
    depends_on:
      - rabbitmq
    environment:
      WEB_HOOK: ${WEB_HOOK}
      BOT_TOKEN: ${BOT_TOKEN}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    ports:
      - "8000:8000"

  stt-worker:
    container_name: stt-worker
    build: stt-worker
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}

  tts-worker:
    container_name: tts-worker
    build: tts-worker
    depends_on:
      - rabbitmq
    environment:
      PLAY_HT_USER_ID: ${PLAY_HT_USER_ID}
      PLAY_HT_API_KEY: ${PLAY_HT_API_KEY}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}

  rabbitmq:
    image: rabbitmq:3.10.7-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"